### ISSUE TITLE
Litestar crash when use the plugin

### ISSUE THREAD

**Issue by KienPS** [cofin/litestar-granian#15]
I'm trying to use granian using the plugin (v0.4.0) in the latest version of Litestar (v2.9.0). However, with a basic setup below:
```python
from __future__ import annotations

from litestar import Controller, Litestar, get

from litestar_granian import GranianPlugin


class SampleController(Controller):
    @get(path="/sample")
    async def sample_route(self) -> dict[str, str]:
        """Sample Route."""
        return {"sample": "hello-world"}


app = Litestar(plugins=[GranianPlugin()], route_handlers=[SampleController])
```
and running ```litestar run```, I get:
```bash
Using Litestar app from app:app
Starting Granian server process ──────────────────────────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────┬──────────────────────┐
│ Litestar version             │ 2.9.0                │
│ Debug mode                   │ Disabled             │
│ Python Debugger on exception │ Disabled             │
│ CORS                         │ Disabled             │
│ CSRF                         │ Disabled             │
│ OpenAPI                      │ Enabled path=/schema │
│ Compression                  │ Disabled             │
└──────────────────────────────┴──────────────────────┘
INFO - 2024-06-10 11:17:19,358 - _granian - server - Starting granian (main PID: 6266)
INFO - 2024-06-10 11:17:19,358 - _granian - server - Listening at: http://127.0.0.1:8000
```
then it crashed.
However, using the granian command ```granian --interface asgi app:app```, it works fine.

**Comment by cofin** [comment]
@KienPS which OS are you running from?  I am not able to reproduce from Linux with the following:
```shell
(.venv) codyfincher@codyfincher-cloudtop:~/code/dma/framework/tmp$ litestar run
Using Litestar app from app:app
Starting Granian server process ─────────────────────────────────────────────────────────
┌──────────────────────────────┬──────────────────────┐
│ Litestar version             │ 2.9.0                │
│ Debug mode                   │ Disabled             │
│ Python Debugger on exception │ Disabled             │
│ CORS                         │ Disabled             │
│ CSRF                         │ Disabled             │
│ OpenAPI                      │ Enabled path=/schema │
│ Compression                  │ Disabled             │
└──────────────────────────────┴──────────────────────┘
INFO - 2024-06-10 21:49:47,241 - _granian - server - Starting granian (main PID: 1270989)
INFO - 2024-06-10 21:49:47,242 - _granian - server - Listening at: http://127.0.0.1:8000
INFO - 2024-06-10 21:49:47,246 - _granian - server - Spawning worker-1 with pid: 1270995
INFO - 2024-06-10 21:49:47,263 - _granian.asgi.serve - serve - Started worker-1
INFO - 2024-06-10 21:49:47,263 - _granian.asgi.serve - serve - Started worker-1 runtime-1
```

**Comment by KienPS** [comment]
> @KienPS which OS are you running from?  I am not able to reproduce from Linux with the following:
> ```shell
> (.venv) ~/code/framework/tmp$ litestar run
> Using Litestar app from app:app
> Starting Granian server process ─────────────────────────────────────────────────────────
> ┌──────────────────────────────┬──────────────────────┐
> │ Litestar version             │ 2.9.0                │
> │ Debug mode                   │ Disabled             │
> │ Python Debugger on exception │ Disabled             │
> │ CORS                         │ Disabled             │
> │ CSRF                         │ Disabled             │
> │ OpenAPI                      │ Enabled path=/schema │
> │ Compression                  │ Disabled             │
> └──────────────────────────────┴──────────────────────┘
> INFO - 2024-06-10 21:49:47,241 - _granian - server - Starting granian (main PID: 1270989)
> INFO - 2024-06-10 21:49:47,242 - _granian - server - Listening at: http://127.0.0.1:8000
> INFO - 2024-06-10 21:49:47,246 - _granian - server - Spawning worker-1 with pid: 1270995
> INFO - 2024-06-10 21:49:47,263 - _granian.asgi.serve - serve - Started worker-1
> INFO - 2024-06-10 21:49:47,263 - _granian.asgi.serve - serve - Started worker-1 runtime-1
> ```

I'm on MacOS 14 (Macbook Pro 2017 with Intel chip).

I'm spend a while to see why it just stop. Turning on debug mode on Pycharm and rerun it, I got to the Exception: ```ValueError: Can't patch loop of type <class 'uv.uvLoop'>```

**Comment by KienPS** [comment]
I have just tried to downgrade to v0.3.0 and it works as expected.

**Comment by KienPS** [comment]
So after a while of debugging, I found out the issue was the ```log_dictconfig```, as it cause an exception:
```
Can't pickle local object '_default_exception_logging_handler_factory.<locals>._default_exception_logging_handler'
```
Currently my temporary way to fix is to remove the ```log_dictconfig``` keyword parameter.

**Comment by KienPS** [comment]
I have made a [pull request](https://github.com/cofin/litestar-granian/pull/16) for this issue. Do you mind reviewing it?

**Comment by cofin** [comment]
I did some testing on a tweak to your PR that I made.  We'll have to do a little more testing because it is raising on exception when I am using it with python 3.12 and the structlog based app in the `examples` folder.

Is there a way that I can reproduce this?  Also, can you let me know what python version you are using?

**Comment by cofin** [comment]
@KienPS I've added one more tweak that appears to work in my environments.  Can you check on your side?

`litestar --app examples.structlog:app run` if you got the repository cloned locally.

**Comment by cofin** [comment]
@KienPS I was able to track down the cause of the pickling issue above.  Can you verify that the latest patch release still works for you?  it should pull over the logging config you have from Litesatr or use the default if there isn't one set

**Comment by KienPS** [comment]
> @KienPS I was able to track down the cause of the pickling issue above. Can you verify that the latest patch release still works for you? it should pull over the logging config you have from Litestar or use the default if there isn't one set

I can verify it still works on my MacOS.
